USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS EVIDENCE_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

CREATE RESOURCE MONITOR IF NOT EXISTS EVIDENCE_RM
  WITH CREDIT_QUOTA = 20
  TRIGGERS ON 75 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;
ALTER WAREHOUSE EVIDENCE_WH SET RESOURCE_MONITOR = EVIDENCE_RM;
ALTER WAREHOUSE COMPUTE_WH  SET AUTO_SUSPEND = 60;

CREATE DATABASE IF NOT EXISTS EVIDENCE_DB
  COMMENT = 'Datathon: breast cancer evidence stress-test. Public documents only.';
CREATE SCHEMA IF NOT EXISTS EVIDENCE_DB.CORE;

-- Team role (least privilege)
CREATE ROLE IF NOT EXISTS EVIDENCE_DEV;
GRANT USAGE ON WAREHOUSE EVIDENCE_WH  TO ROLE EVIDENCE_DEV;
GRANT USAGE ON DATABASE  EVIDENCE_DB  TO ROLE EVIDENCE_DEV;
GRANT ALL   ON SCHEMA    EVIDENCE_DB.CORE TO ROLE EVIDENCE_DEV;
GRANT DATABASE ROLE SNOWFLAKE.PYPI_REPOSITORY_USER TO ROLE EVIDENCE_DEV;   -- lets OCR_IMAGE use Snowflake's PyPI copy
GRANT ROLE EVIDENCE_DEV TO ROLE SYSADMIN;

-- One line per teammate
GRANT ROLE EVIDENCE_DEV TO USER TUSHARDAS;