USE ROLE EVIDENCE_DEV;
USE WAREHOUSE EVIDENCE_WH;
USE SCHEMA EVIDENCE_DB.CORE;

CREATE STAGE IF NOT EXISTS DOCS_STAGE
  DIRECTORY = (ENABLE = TRUE) ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  COMMENT = 'PDF, TXT, MD and JSON documents. Public only, no personal data.';

CREATE STAGE IF NOT EXISTS IMAGES_STAGE
  DIRECTORY = (ENABLE = TRUE) ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  COMMENT = 'Images for OCR. Public only, no personal data.';

CREATE FILE FORMAT IF NOT EXISTS JSON_FF TYPE = JSON STRIP_OUTER_ARRAY = TRUE;